openapi: 3.0.0
info:
  title: API de Traitement d'Images
  version: 1.0.0
  description: API pour la conversion, la compression et le redimensionnement des images.
servers:
  - url: http://localhost:8050/api
    description: Serveur de développement
paths:
  /convert:
    post:
      summary: Convertir une image dans un format différent
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Image convertie avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  buffer:
                    type: string
                    format: binary
                  originalname:
                    type: string
                  mimetype:
                    type: string
        '400':
          description: Aucun fichier téléchargé
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Erreur lors du traitement de l'image
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /compress:
    post:
      summary: Compresser une image
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Image compressé avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  buffer:
                    type: string
                    format: binary
                  originalname:
                    type: string
                  mimetype:
                    type: string
        '400':
          description: Aucun fichier téléchargé
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Erreur lors de la compression de l'image
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /multi-size:
    post:
      summary: Générer plusieurs tailles d'une image
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                sizes:
                  type: string
                  description: JSON string with desktop, tablet, and mobile sizes
                quality:
                  type: string
                  description: Quality of the output images
      responses:
        '200':
          description: Plusieurs tailles d'image générées avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    desktop:
                      type: object
                      properties:
                        buffer:
                          type: string
                        originalname:
                          type: string
                        mimetype:
                          type: string
                    tablet:
                      type: object
                      properties:
                        buffer:
                          type: string
                        originalname:
                          type: string
                        mimetype:
                          type: string
                    mobile:
                      type: object
                      properties:
                        buffer:
                          type: string
                        originalname:
                          type: string
                        mimetype:
                          type: string
        '400':
          description: Aucun fichier téléchargé
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Erreur lors de la génération des tailles d'image
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string